In [1]:
import pandas as pd
import numpy as np

In [2]:
data1=pd.read_csv("data/modeling_numeric.csv", index_col=None) # Less Columns

In [3]:
data1.drop(columns=[ "title_bout","weight_diff_red-blue","height_diff_red-blue"], inplace=True)

In [4]:
from sklearn.model_selection import train_test_split

In [6]:
X=data1.drop('Winner',axis=1,inplace=False)
y = data1['Winner']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=69)

## Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
logmodel= LogisticRegression(max_iter = 10000)
logmodel.fit(X, y)
logmodel.score(X,y)

0.6779558512246749

In [9]:
logmodel = LogisticRegression(max_iter = 10000)
logmodel.fit(X_train, y_train)
logmodel.score(X_test,y_test)

0.6842900302114804

In [10]:
y_pred_logmodel = logmodel.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report

In [13]:
print(classification_report(y_test, y_pred_logmodel ))

              precision    recall  f1-score   support

           0       0.56      0.37      0.45       228
           1       0.72      0.85      0.78       434

    accuracy                           0.68       662
   macro avg       0.64      0.61      0.61       662
weighted avg       0.67      0.68      0.66       662



##  SVC (Support Vector Classification)

In [14]:
from sklearn.svm import SVC


In [15]:
svc = SVC()

In [16]:
svc.fit(X_train, y_train)
svc.score(X_test,y_test)

0.6555891238670695

In [17]:
y_pred_svc = svc.predict(X_test)

In [18]:
confusion_matrix(y_test, y_pred_svc)

array([[  0, 228],
       [  0, 434]], dtype=int64)

## K-Nearest Neighbor (KNN)

In [19]:
from sklearn.neighbors import KNeighborsClassifier


In [20]:
knn = KNeighborsClassifier()

In [21]:
knn.fit(X_train, y_train)
knn.score(X_test,y_test)

0.6193353474320241

In [22]:
y_pred_knn = knn.predict(X_test)

In [23]:
confusion_matrix(y_test, y_pred_knn)


array([[ 85, 143],
       [109, 325]], dtype=int64)

## XGB Classifier

In [29]:
from xgboost import XGBClassifier

In [30]:
xgb = XGBClassifier()

In [31]:
xgb.fit(X_train, y_train)
xgb.score(X_test,y_test)

0.648036253776435

In [32]:
y_pred_xgb = xgb.predict(X_test)

In [33]:
confusion_matrix(y_test, y_pred_xgb)

array([[ 84, 144],
       [ 89, 345]], dtype=int64)

## Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.6918429003021148

In [26]:
y_pred_rf = rf.predict(X_test)

In [27]:
confusion_matrix(y_test, y_pred_rf)

array([[ 66, 162],
       [ 42, 392]], dtype=int64)